name: nebula_app
description: Nebula Network — Blockchain Descentralizada, Chat E2EE e Armazenamento Distribuído
version: 3.0.0+3
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.3
  pointycastle: ^3.9.1
  qr_flutter: ^4.1.0
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.5
  intl: ^0.19.0
  network_info_plus: ^6.1.0
  nearby_connections: ^4.3.0
  permission_handler: ^11.3.1
  bip39: ^1.0.6
  path_provider: ^2.1.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
